### ISSUE TITLE
Typo: cg_grid_bounding_box_write -> cg_grid_bounding_box_read

### ISSUE THREAD

**Issue by awoimbee** [CGNS/cgns-archives#24]
At https://cgns.github.io/CGNS_docs_current/midlevel/grid.html, more precisely at https://github.com/CGNS/cgns.github.io/blob/3376750b507800dec0b7a40c3ceb8379f3b7bfd0/CGNS_docs_current/midlevel/grid.html#L158
`cg_grid_bounding_box_write` should actually be `cg_grid_bounding_box_read`.

**Comment by brtnfld** [comment]
Thanks, fixed.
